package org.etsi.osl.tmf.pm628.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import javax.annotation.Generated;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = PerformanceMeasurement.class, name = "PerformanceMeasurement"),
  @JsonSubTypes.Type(value = PerformanceMeasurementAtomic.class, name = "PerformanceMeasurementAtomic"),
  @JsonSubTypes.Type(value = PerformanceMeasurementGroup.class, name = "PerformanceMeasurementGroup"),
  @JsonSubTypes.Type(value = PerformanceMeasurementRef.class, name = "PerformanceMeasurementRef")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-15T07:30:16.936523289Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public interface PerformanceMeasurementRefOrValue {
    public String getAtType();
}
