package org.etsi.osl.tmf.pm628.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Embeddable;

import javax.annotation.Generated;
import java.util.Objects;

/**
 * ProtocolTransferData
 */

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = FileTransferData.class, name = "FileTransferData"),
  @JsonSubTypes.Type(value = FileTransferDataMVO.class, name = "FileTransferData_MVO")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-15T07:30:16.936523289Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
@Embeddable
public class ProtocolTransferData {

  @JsonProperty("transportProtocol")
  private String transportProtocol;

  public ProtocolTransferData transportProtocol(String transportProtocol) {
    this.transportProtocol = transportProtocol;
    return this;
  }

  /**
   * Get transportProtocol
   * @return transportProtocol
  */
  
  @Schema(name = "transportProtocol", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("transportProtocol")
  public String getTransportProtocol() {
    return transportProtocol;
  }

  public void setTransportProtocol(String transportProtocol) {
    this.transportProtocol = transportProtocol;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtocolTransferData protocolTransferData = (ProtocolTransferData) o;
    return Objects.equals(this.transportProtocol, protocolTransferData.transportProtocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transportProtocol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtocolTransferData {\n");
    sb.append("    transportProtocol: ").append(toIndentedString(transportProtocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

